### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by wzhou1974** [asutton/origin#12]
In file included from /home/walter/workspace/study/asutton-origin-4358f0d/origin/memory/memory.cpp:4:
/home/walter/workspace/study/asutton-origin-4358f0d/origin/memory/memory.hpp: In function ‘void origin::construct(T*, Args&& ...)’:
/home/walter/workspace/study/asutton-origin-4358f0d/origin/memory/memory.hpp:25:46: error: return-statement with a value, in function returning ‘void’ [-fpermissive]
   return new(p) T(std::forward<Args>(args)...);

**Comment by wzhou1974** [comment]
build on Ubuntu 18.04
